- name: Install nginx
  yum:
    name: nginx
    state: installed

- name: Download Frontend Code
  get_url:
    url: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip

- name: Remove Old Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
